### ISSUE TITLE
Timeline of Policy and Idp Connections Resources

### ISSUE THREAD

**Issue by kyogendra08** [pingidentity/terraform-provider-pingfederate#208]
Hi Team, 

I am implementing Ping Federate as code and currently am missing the following resources from your provider: 
- SP - Idp Connections Resource
- Authentication Policies - Policy Resource

Do you know the time line in which it will be available ? 

Thank You !

**Comment by wesleymccollam** [comment]
@Keetika-Yogendra, there is no official timeline for these resources. However, I've marked them as a higher priority internally. I will do my best to update you when they're available.

**Comment by patrickcping** [comment]
hey @Keetika-Yogendra - as Wes says, we don't have an official date as yet for these resources, but they will be there for the `v1` release later in the year.  Our delivery is driven by customer priorities, so if not having these resources starts impacting delivery, please get in touch with us directly through your customer or partner account team so we can understand the impact better and we know how to prioritise against other ongoing work

Otherwise, stay tuned, they are on the work queue

Thanks!

**Comment by carloprone** [comment]
+1 to this request!

In my company we are keen to adopt this adapter, but we really need these two resources.
The others still missing we can do without, but Authentication Policies and SP IdP Conn are essential resources, basically the core of the whole product config.

Thanks in advance, cheers!

**Comment by patrickcping** [comment]
For those watching, `pingfederate_authentication_policies` was released yesterday in version `0.11`: [docs link](https://registry.terraform.io/providers/pingidentity/pingfederate/latest/docs/resources/authentication_policies).

Importing policies to Terraform is the recommendation here:
- [Import command](https://developer.hashicorp.com/terraform/cli/import)
- [Import block](https://developer.hashicorp.com/terraform/language/import)

There were bugs fixed in the Terraform CLI to support the use of the Import blocks.  If you try to use Import block with the `pingfederate_authentication_policies` resource and you see a panic crash, please update your Terraform to v1.8.4 or higher

The SP - IdP Connections Resource is coming next

**Comment by henryrecker-pingidentity** [comment]
`pingfederate_sp_idp_connection` is available in version 1.0.0 of the provider on the registry.
